### ISSUE TITLE
Ox.parse support for IO

### ISSUE THREAD

**Issue by jturkel** [ohler55/ox#130]
It looks like the SAX parsing (i.e. `Ox.sax_parse`) supports reading from IO stream. It would be nice if the DOM parsing (i.e. `Ox.parse`) also supported reading from IO stream. This would come in handy when reading from a compressed stream, network stream, etc. The workaround is to read the stream entirely into memory before parsing which increases memory usage.

**Comment by ohler55** [comment]
Someone else ran into that today as well. I'll add that to the next release.

**Comment by ohler55** [comment]
Please try the version I just pushed to github.

**Comment by jturkel** [comment]
It still doesn't work for me. Perhaps I'm doing something wrong?

```
>> Zlib::GzipReader.open('/Users/jturkel/Downloads/note.xml.gz') do |gz|
  Ox.parse(gz)
end

TypeError: wrong argument type Zlib::GzipReader (expected String)
	from (irb):2:in `parse'
	from (irb):2:in `block in irb_binding'
	from (irb):1:in `open'
	from (irb):1
	from /Users/jturkel/.rvm/gems/ruby-2.2.4@dandelion/gems/railties-4.1.14.1/lib/rails/commands/console.rb:90:in `start'
	from /Users/jturkel/.rvm/gems/ruby-2.2.4@dandelion/gems/railties-4.1.14.1/lib/rails/commands/console.rb:9:in `start'
	from /Users/jturkel/.rvm/gems/ruby-2.2.4@dandelion/gems/railties-4.1.14.1/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/jturkel/.rvm/gems/ruby-2.2.4@dandelion/gems/railties-4.1.14.1/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/jturkel/.rvm/gems/ruby-2.2.4@dandelion/gems/railties-4.1.14.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/jturkel/salsify/dandelion/script/rails:6:in `require'
	from /Users/jturkel/salsify/dandelion/script/rails:6:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
```

**Comment by ohler55** [comment]
What type is gz? Not a string I would guess.

**Comment by jturkel** [comment]
It's a [Zlib::GzipReader](http://ruby-doc.org/stdlib-2.2.4/libdoc/zlib/rdoc/Zlib/GzipReader.html) which is an [IO](http://ruby-doc.org/core-2.2.4/IO.html) like object.

**Comment by ohler55** [comment]
I'll look at it tonight. Have you tried Oj.load?

**Comment by jturkel** [comment]
Same problem with `Oj.load`. Thanks for looking into it.

**Comment by ohler55** [comment]
I was away from a computer earlier today. Once I had a chance to look, Oj.load() and Oj.parse() do not support IO objects. The Oj.sax_parse() does support IO objects though.
