### ISSUE TITLE
Compilation error when HAVE_RB_ENC_ASSOCIATE is not defined.

### ISSUE THREAD

**Issue by sylvain-8422** [ohler55/ox#268]
C code is not valid (missing `}`) when `HAVE_RB_ENC_ASSOCIATE` is not defined:

https://github.com/ohler55/ox/blob/1fefe9840be0e556afc27e0dc6a9aa5d13a92cf6/ext/ox/gen_load.c#L118-L131

**Comment by ohler55** [comment]
Will get it fixed tonight.

**Comment by ohler55** [comment]
fixed and released

**Comment by sylvain-8422** [comment]
Unfortunately, the code still does not compile when `rb_enc_associate` is not available:

```
obj_load.c:68:2: error: implicit declaration of function 'rb_enc_associate' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        rb_enc_associate(rstr, (rb_encoding*)encoding);
```

```
obj_load.c:92:6: error: implicit declaration of function 'rb_enc_associate' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            rb_enc_associate(rstr, (rb_encoding*)encoding);
```

On our side, we fixed the issue by making `rb_enc_associate` available, but it would not compile without `rb_enc_associate`.

It is not an issue for us anymore, but it might be for other people.

**Comment by ohler55** [comment]
If `rb_enc_associate` is not available then `HAVE_RB_ENC_ASSOCIATE` should not be defined. That is the whole purpose of `HAVE_RB_ENC_ASSOCIATE`. The extconf.rb file should check and define that. Under what circumstances did you find that the extconf.rb failed?

**Comment by sylvain-8422** [comment]
From my previous comment:

https://github.com/ohler55/ox/blob/3e97ceab84e829bf9153daad9e9134173b85943f/ext/ox/obj_load.c#L64-L73

https://github.com/ohler55/ox/blob/3e97ceab84e829bf9153daad9e9134173b85943f/ext/ox/obj_load.c#L87-L101

`HAVE_RUBY_ENCODING_H` was defined, but not `HAVE_RB_ENC_ASSOCIATE`.

So it tried to compile both blocks and failed on `rb_enc_associate`.

How to reproduce:

- Have `HAVE_RUBY_ENCODING_H` defined ;
- Do not have `HAVE_RB_ENC_ASSOCIATE` defined (`rb_enc_associate` not available) ;
- Try to compile `obj_load.c`.

**Comment by sylvain-8422** [comment]
It may also fail elsewhere, but as I said earlier, we just made `rb_enc_associate` available and moved on.

**Comment by ohler55** [comment]
Did you customize the Makefile after it was generated to define `HAVE_RUBY_ENCODING_H`?

The `extconf.rb` checks to see if `rb_enc_associate` is defined and sets `HAVE_RUBY_ENCODING_H` accordingly. I understand that modifying the Makefile will break things but that is not something I can guard against. If, on the other hand, there is a system (Ruby version, OS, etc) that fails then that needs to be fixed.

**Comment by sylvain-8422** [comment]
It was failing for a co-worker, when running a `bundle install` that was updating `ox` to the latest version.

Sources were not modified.

As I was not having the same issue, `HAVE_RB_ENC_ASSOCIATE` was defined on my workstation, I suggested that he tries to recompile his Ruby runtime.

After that, his `HAVE_RB_ENC_ASSOCIATE` was defined, and everything was OK.

So, unfortunately, I cannot tell what caused `HAVE_RUBY_ENCODING_H` to be defined while `HAVE_RB_ENC_ASSOCIATE` was not.

I would close this issue and wait and see if someone else ever has this same issue.

**Comment by ohler55** [comment]
Okay, thanks. Maybe closing is best for now and reopen if it can be reproduced in a definable environment. At least the compile error was identified and fixed even if there may be a lurking Makefile generation issue waiting out there.
